### ISSUE TITLE
Issue with running code

### ISSUE THREAD

**Issue by osleland** [FranckLab/single-layer-3D-TFM#1]
I've successfully downloaded Matlab (+ necessary add ons), Docker Desktop, the code which is added to the Matlab path. The first issue I have is that when running
> SL3DTFM_runscript.m

I get the error
>Unable to resolve the name 'SL3DTFM_runscript.m'.

When inspecting the code files, I found a similar file called SL3DTFM_runfile.m and when I ran that, I got the error:

>Error using save
Cannot create 'example_data_example_saved_data_all_settings.mat' because
'C:\Users\Pacu-2\Documents\MATLAB\single-layer-3D-TFM-master\SL_3D_TFM_code\example_data'
does not exist.

>Error in SL3DTFM_runfile (line 58)
save([data_dir,data_name,'_',save_file_descriptor,'_','all','_settings.mat'], '-v7.3')
 
In the instructions, it says to download the example data in the example folder, which I can do, but since the files are named differently I want to confirm that I'm using the correct code.

**Comment by ALandauer** [comment]
1. Yes, it should read `SL3DTFM_runfile.m` - we must have changed the name file name at some point and not updated the readme, thanks for point that out.
2.  If you look at the directory structure, once you unzip the example data of course, it should look something like this:
![image](https://user-images.githubusercontent.com/12899180/181850847-b64c4f36-1447-44e9-a965-bc3cc6108b18.png)
and the `SL_3D_TFM_code` folder should look like:
![image](https://user-images.githubusercontent.com/12899180/181852864-ca088005-c191-4e2a-b916-e8177512dae5.png)
sometimes unzipping will be problematic depending on the tool used to unzip. Once it runs past line 58 it will save a new `example_data_example_saved_data_all_settings.mat` file into the `example_data` folder. When I downloaded and ran a fresh version of it, mine didn't replicate the same issue, so its a bit of a guessing game. Happy to help debug it with you though.
