### ISSUE TITLE
Error With inpaint_nans3.m

### ISSUE THREAD

**Issue by oleland-br** [FranckLab/single-layer-3D-TFM#2]
I successfully ran SL3DTFM_runfile.m in Matlab and run_sl_tfm_ps.ps1 in PowerShell and saved my sl_tfm_call_XYpoint_name_1.py and *2.py. When I tried running SL3DTFM_postFEniCS.m I got the following error where the script couldn't find inpaint_nans.m.
![image](https://github.com/FranckLab/single-layer-3D-TFM/assets/136110894/e574c3f7-ead6-4a7c-93e6-017adb80405e)

I see that inpaint_nans.m is provided so I added a 3 to inpaint_nans on line 74 of funCalculateTractions.m and got the following error
![image](https://github.com/FranckLab/single-layer-3D-TFM/assets/136110894/485d177c-dd87-4b7f-8e7f-1b9dace7f4bd)

Is this an issue with inpaint_nans3.m or how I'm running the code? The .py files are save in the same directory as the _fenicsOut files. Right now I'm just processing the provided example_data

**Comment by ALandauer** [comment]
The 3D and 2D version of inpaint_nans are different codes (both from John D'Errico on the FileExchange) that expect different dimensionalality in the input. Since it seems to be missing, I added the 2D version of the function to the `code' folder - see if that works as expected now.

 -- Alex

**Comment by oleland-br** [comment]
Hi Alex, the code ran perfectly with the inpaint_nans.m in the code folder. Many thanks

**Comment by ALandauer** [comment]
Excellent, thanks for letting me know.
